import { Activity, ArrowRight, Building2, Check, ClipboardCheck, CloudSun, Compass, Database, Flame, Gauge, Globe2, Handshake, Layers3, Leaf, Map, MapPin, Network, RadioTower, RefreshCw, Settings2, ShieldCheck, Sparkles, Target, Timer, TrendingUp, Trees, Users, Zap } from "lucide-react";
import { SectionHeading } from "@/components/ui/section-heading";
import { Button } from "@/components/ui/button";
import { PLATFORM_URL } from "@/lib/constants";

const problems = ["Informação fragmentada", "Leitura técnica pouco acessível", "Falta de personalização local", "Dificuldade em comparar zonas", "Tempo perdido na preparação", "Dependência de várias plataformas"];
const features = [
  [MapPin, "Previsão localizada", "Condições meteorológicas organizadas para as localizações relevantes de cada território."],
  [Gauge, "Índices técnicos", "Indicadores de risco apresentados com uma leitura visual clara e consistente."],
  [Layers3, "Comparação territorial", "Consulta e comparação de diferentes zonas numa única interface."],
  [RefreshCw, "Atualização automática", "Informação atualizada sem tarefas manuais de recolha e organização."],
  [CloudSun, "Evolução diária", "Visualização do dia atual e dos dias seguintes para apoiar a preparação."],
  [Globe2, "Acesso simples", "Interface responsiva disponível no navegador, sem instalação necessária."],
];
const indices = [
  ["FWI", "Fire Weather Index", "Síntese das condições meteorológicas associadas à intensidade potencial do fogo."],
  ["ISI", "Initial Spread Index", "Indicador da rapidez potencial de propagação inicial do fogo."],
  ["BUI", "Build Up Index", "Representa a disponibilidade de combustível para combustão."],
  ["FFMC", "Fine Fuel Moisture Code", "Reflete a humidade dos combustíveis finos à superfície."],
  ["DMC", "Duff Moisture Code", "Indica a secura das camadas orgânicas pouco profundas."],
  ["DC", "Drought Code", "Representa a secura acumulada nas camadas orgânicas profundas."],
  ["SSR", "Seasonal Severity Rating", "Apoia a leitura da severidade acumulada ao longo de um período sazonal."],
  ["DSR", "Daily Severity Rating", "Traduz a severidade diária das condições de perigo meteorológico."],
];

export function ProblemSection() { return <section className="section problem" id="problema"><div className="container problem-grid"><div><SectionHeading eyebrow="O desafio" title="Decisões críticas ainda dependem de informação dispersa." text="Para compreender as condições meteorológicas, o risco de incêndio e a evolução diária, as equipas consultam frequentemente fontes diferentes. O resultado é uma leitura mais lenta e menos consistente."/><div className="problem-list">{problems.map((x,i)=><div key={x}><span>{String(i+1).padStart(2,"0")}</span>{x}</div>)}</div></div><div className="map-card" aria-hidden="true"><div className="map-topo"/><span className="map-pin map-pin--1"><i/>Zona norte</span><span className="map-pin map-pin--2"><i/>Zona central</span><span className="map-pin map-pin--3"><i/>Zona sul</span><div className="source-card source-card--1"><CloudSun/>Meteorologia <b>Fonte 01</b></div><div className="source-card source-card--2"><Flame/>Índices <b>Fonte 02</b></div><div className="source-card source-card--3"><Map/>Território <b>Fonte 03</b></div><div className="map-caption"><Network/><span><strong>Fontes dispersas</strong><small>Mais tempo entre a consulta e a decisão</small></span></div></div></div></section> }

export function SolutionSection() { return <><section className="section solution" id="solucao"><div className="container"><SectionHeading eyebrow="A solução" title="Uma visão única sobre o risco no território." text="O FireIndex centraliza e organiza dados meteorológicos e índices técnicos relevantes numa interface simples, localizada e adaptada à utilização operacional." align="center"/><div className="feature-grid">{features.map(([Icon,title,text])=><article key={title as string}><span className="icon-box"><Icon/></span><h3>{title as string}</h3><p>{text as string}</p><span className="feature-check"><Check/> Disponível na plataforma</span></article>)}</div></div></section><section className="section indices"><div className="container"><div className="indices-head"><SectionHeading eyebrow="Leitura técnica simplificada" title="Índices apresentados pela plataforma." text="Um conjunto de indicadores do sistema canadiano FWI, organizado para facilitar uma leitura rápida sem perder o rigor técnico."/><div className="scale-card"><span>Escala visual de risco</span><div><i/><i/><i/><i/><i/></div><small><span>Baixo</span><span>Muito elevado</span></small></div></div><div className="index-grid">{indices.map(([code,name,text],i)=><article key={code}><div className={`index-code index-code--${(i%4)+1}`}>{code}</div><div><h3>{name}</h3><p>{text}</p></div></article>)}</div><div className="notice"><ShieldCheck/><p><strong>Nota de utilização responsável</strong>O FireIndex apoia a leitura operacional da informação disponível e não substitui orientações, alertas ou determinações emitidas pelas autoridades competentes.</p></div></div></section></> }

const steps = [[Database,"Recolha","Os dados meteorológicos são obtidos a partir de fontes digitais adequadas."],[Settings2,"Processamento","A informação é organizada por localização, data e indicador."],[Activity,"Visualização","Os dados são apresentados numa interface simples e adaptada à leitura operacional."],[Compass,"Decisão","As equipas utilizam a informação como suporte à preparação, vigilância e planeamento."]];
const uses = [[Flame,"Preparação operacional","Apoio à consulta diária dos corpos de bombeiros."],[Building2,"Proteção civil municipal","Leitura territorial para apoiar o planeamento municipal."],[Trees,"Gestão florestal","Acompanhamento das condições relevantes para o território."],[Users,"Equipas e recursos","Informação de suporte à organização e prontidão."],[ShieldCheck,"Prevenção","Preparação mais informada para períodos críticos."],[Map,"Análise territorial","Comparação simples entre várias localizações."],[TrendingUp,"Risco elevado","Acompanhamento da evolução meteorológica prevista."],[RadioTower,"Comunicação interna","Uma referência comum para a leitura entre equipas."]];
export function HowAndUses(){return <><section className="section how" id="como-funciona"><div className="container"><SectionHeading eyebrow="Como funciona" title="Dos dados à informação operacional." text="Um processo contínuo que transforma dados dispersos numa leitura territorial clara." align="center"/><div className="steps">{steps.map(([Icon,title,text],i)=><article key={title as string}><span className="step-number">0{i+1}</span><span className="step-icon"><Icon/></span><h3>{title as string}</h3><p>{text as string}</p>{i<3&&<ArrowRight className="step-arrow"/>}</article>)}</div></div></section><section className="section uses" id="aplicacoes"><div className="container"><div className="uses-heading"><SectionHeading eyebrow="Aplicações" title="Informação útil em diferentes contextos."/><p>Do planeamento diário à gestão do território, o FireIndex adapta a mesma abordagem a diferentes necessidades institucionais.</p></div><div className="uses-grid">{uses.map(([Icon,title,text])=><article key={title as string}><Icon/><div><h3>{title as string}</h3><p>{text as string}</p></div></article>)}</div></div></section></>}

const pilotChecks=["Necessidade operacional identificada no terreno","Ferramenta adaptada ao concelho","Múltiplas localizações configuradas","Previsões e índices numa única consulta","Atualização automática da informação","Acesso simples através de navegador"];
export function PilotSection(){return <><section className="section pilot" id="bvaav"><div className="container pilot-grid"><div><SectionHeading eyebrow="Primeira implementação" title="Criado no terreno. Utilizado em contexto operacional." text="A primeira implementação do FireIndex foi desenvolvida para os Bombeiros Voluntários de Albergaria-a-Velha, a partir de uma necessidade concreta de organizar a informação usada na preparação diária."/><div className="pilot-checks">{pilotChecks.map(x=><span key={x}><Check/>{x}</span>)}</div><Button href={PLATFORM_URL} external>Consultar plataforma operacional <ArrowRight size={17}/></Button><p className="pilot-note">Esta plataforma constitui a primeira implementação operacional do FireIndex.</p></div><div className="photo-placeholder"><div className="terrain-lines"/><div className="photo-badge"><span>BVAAV</span><strong>Albergaria-a-Velha</strong><small>Primeira entidade utilizadora</small></div><div className="photo-label"><Sparkles/><span><strong>Espaço preparado para registo BVAAV</strong><small>Imagem institucional ou operacional</small></span></div></div></div></section><ImplementationProcess/></>}
function ImplementationProcess(){const items=[[Target,"Identificação da necessidade"],[Zap,"Desenvolvimento da solução"],[MapPin,"Configuração do território"],[Users,"Disponibilização às equipas"],[Network,"Replicação noutras entidades"]];return <section className="implementation"><div className="container"><div className="implementation-head"><span className="eyebrow eyebrow--light">Da necessidade à utilização operacional</span><h2>Um modelo construído para ser implementado.</h2></div><div className="implementation-line">{items.map(([Icon,text],i)=><div key={text as string}><span>{i+1}<Icon/></span><strong>{text as string}</strong></div>)}</div></div></section>}

const impacts=[{icon:Timer,title:"Impacto operacional",items:["Menos tempo na consulta de informação","Leitura mais rápida dos indicadores","Melhor preparação das equipas","Maior consistência na consulta diária","Várias localizações numa plataforma"]},{icon:Leaf,title:"Impacto ambiental",items:["Apoio à prevenção","Preparação para períodos críticos","Melhoria da capacidade de resposta","Proteção da floresta e do território","Adaptação a fenómenos extremos"]},{icon:Handshake,title:"Impacto social e económico",items:["Inovação dentro dos corpos de bombeiros","Transferência de conhecimento","Implementação através de uma solução replicável","Apoio a entidades com menor capacidade tecnológica","Serviços especializados de implementação"]}];
export function ImpactSection(){return <section className="section impact" id="impacto"><div className="container"><SectionHeading eyebrow="Impacto" title="Mais clareza para proteger melhor o território." text="O valor do FireIndex está na forma como a informação apoia pessoas, equipas e entidades na sua preparação." align="center"/><div className="impact-grid">{impacts.map(({icon:Icon,title,items})=><article key={title}><Icon/><h3>{title}</h3>{items.map(x=><span key={x}><Check/>{x}</span>)}</article>)}</div><div className="metrics-placeholder"><div><Activity/><span><strong>Métricas de utilização</strong><small>Área preparada para dados reais</small></span></div><div><Trees/><span><strong>Cobertura territorial</strong><small>Área preparada para dados reais</small></span></div><div><Users/><span><strong>Entidades utilizadoras</strong><small>Área preparada para dados reais</small></span></div></div></div></section>}

const growth=["Implementação noutros corpos de bombeiros","Configuração das localizações relevantes","Adaptação a municípios e proteção civil","Utilização por entidades de gestão florestal","Instalação, parametrização e formação","Acompanhamento técnico e licenciamento","Integrações específicas quando necessárias","Reinvestimento na manutenção da solução"];
const differences=[[Target,"Nasce de uma necessidade concreta"],[Users,"Desenvolvido próximo dos utilizadores"],[ClipboardCheck,"Orientado para a operação"],[MapPin,"Configurado por território"],[Layers3,"Agrega diferentes indicadores"],[Network,"Modelo replicável"],[Gauge,"Estrutura tecnológica acessível"],[ShieldCheck,"Missão social e territorial"]];
export function ScaleAndDifference(){return <><section className="section scale"><div className="container scale-grid"><div><SectionHeading eyebrow="Escalabilidade" title="Uma solução local, preparada para diferentes territórios."/><blockquote>“Desenvolvido a partir da experiência operacional dos Bombeiros Voluntários de Albergaria-a-Velha, o FireIndex pode ser configurado para diferentes territórios, permitindo que outros corpos de bombeiros, municípios e entidades florestais utilizem a mesma abordagem com informação adaptada à sua realidade local.”</blockquote><p>O FireIndex é um serviço tecnológico promovido pelos BVAAV e disponível para outras entidades, com configuração, formação e acompanhamento adequados a cada contexto.</p></div><div className="growth-list"><h3>Modelo de implementação</h3>{growth.map((x,i)=><div key={x}><span>{String(i+1).padStart(2,"0")}</span>{x}</div>)}</div></div></section><section className="section differentiation"><div className="container"><SectionHeading eyebrow="Diferenciação" title="Tecnologia desenvolvida a partir da operação real." text="Uma solução em que a utilidade operacional, a adaptação local e a missão de proteção do território orientam cada escolha."/><div className="difference-grid">{differences.map(([Icon,text])=><article key={text as string}><Icon/><strong>{text as string}</strong></article>)}</div></div></section></>}

export function CTASection(){return <section className="cta"><div className="container cta-inner"><div><span className="eyebrow eyebrow--light">Implementação</span><h2>Leve o FireIndex para o seu território.</h2><p>Se representa uma entidade que pretende utilizar o FireIndex no seu território, contacte-nos. A solução pode ser configurada para bombeiros, municípios, proteção civil, entidades florestais e outras organizações responsáveis pela proteção do território.</p></div><div><Button href="#contacto" variant="light">Contacte-nos <ArrowRight size={17}/></Button><Button href={PLATFORM_URL} external variant="secondary">Ver plataforma BVAAV</Button></div></div></section>}
